### ISSUE TITLE
Don't want to use CMAKE_PROJECT_TOP_LEVEL_INCLUDES

### ISSUE THREAD

**Issue by laxmij-cmd** [conan-io/cmake-conan#595] opened 2023-11-20 10:48 UTC
### What is your question?

Hi,

We are about to migrateto conan 2.0 using cmake. https://github.com/conan-io/cmake-conan/tree/develop2 says 

cmake -B build -S . -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=../conan_provider.cmake -DCMAKE_BUILD_TYPE=Release

but in our organization, we don't want to pass extra parameter to cmake as it will result in lot of work in modifying existing automation. Is there any way I can use cmake-conan without providing extra parameter CMAKE_PROJECT_TOP_LEVEL_INCLUDES?

Best Regards
Laxmi

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-11-20 11:36
> but in our organization, we don't want to pass extra parameter to cmake as it will result in lot of work in modifying existing automation. Is there any way I can use cmake-conan without providing extra parameter CMAKE_PROJECT_TOP_LEVEL_INCLUDES?

Sure, the modern recommended way is to use CMakePresets. 

In any case, migration from Conan 1.X old ``cmake-conan`` integration already requires removing a ton of things from ``CMakeLists.txt`` files. So adding one extra argument in the automation probably would be a small change compared with that? Also, the Conan 2.0 cli is different, so the automation scripts will have to be modified anyway to be ready for Conan 2.0, I think adding this argument probably would not be the only necessary change.

**Comment by laxmij-cmd** [comment] 2023-11-21 06:27
Sorry, this solution of using CMakePresets will not work for us.

**Comment by valgur** [comment] 2023-11-21 07:02
Adding
```cmake
include(conan_provider.cmake)
```
above `project()` works fine, if that helps.

For an example, here's a project where I further wrapped it in a separate `third_party.cmake` and included it at the top of CMakeLists.txt: https://github.com/valgur/novatel_edie/blob/main/cmake/third_party.cmake

**Comment by laxmij-cmd** [comment] 2023-11-21 10:09
Adding 

include(conan_provider.cmake) above project() doesn't work for me

![image](https://github.com/conan-io/conan/assets/111378770/3fd5f668-5649-402b-aafb-8ad48da243db)

Error is

![image](https://github.com/conan-io/conan/assets/111378770/c27050a7-5e1d-4ff7-8e88-91d385dc24b4)

**Comment by laxmij-cmd** [comment] 2023-11-21 10:10
cmake version is 3.24

**Comment by memsharded** [comment] 2023-11-21 10:49
Moving this to cmake-conan repo

**Comment by memsharded** [comment] 2023-11-21 10:57
Maybe the issue is that the ``include()`` should be the first thing, I think better before the ``cmake_minimum_required()``, but also it should be in the root ``CMakeLists.txt``, it seems it cannot go in a sub-project ``CMakeLists.txt``.

> Sorry, this solution of using CMakePresets will not work for us.

This seems a conversation out of Conan scope. Conan is just implementing the standard and defined CMake mechanisms to integrate with CMake. Maybe this could be a feature request to CMake, to allow the inclusion of providers from ``CMakeLists.txt`` instead of using ``CMAKE_PROJECT_TOP_LEVEL_INCLUDES``?

**Comment by valgur** [comment] 2023-11-21 11:05
> Maybe the issue is that the include() should be the first thing, I think better before the cmake_minimum_required(), but also it should be in the root CMakeLists.txt, it seems it cannot go in a sub-project CMakeLists.txt.

Yeah, it needs to be at the root and before `project(...)`. The order of `cmake_minimum_required()` does not matter (https://github.com/valgur/novatel_edie/blob/main/CMakeLists.txt#L1-L4).

**Comment by laxmij-cmd** [comment] 2023-11-21 12:39
below command when included at the very beginning or after cmake_minimum_required in CMakeLists.txt
    include(${CMAKE_CURRENT_SOURCE_DIR}/conan_provider.cmake)
always results in error
    
![image](https://github.com/conan-io/cmake-conan/assets/111378770/a29bbf99-b732-4cbd-86bd-cb92038fe253)

but when I created new cmake file e.g new.cmake with content as

list(APPEND CMAKE_PROJECT_TOP_LEVEL_INCLUDES ${CMAKE_CURRENT_SOURCE_DIR}/conan_provider.cmake)

and included this file in CMakeLists.txt before project() command, it worked.

**Comment by memsharded** [comment] 2023-11-21 14:19
> list(APPEND CMAKE_PROJECT_TOP_LEVEL_INCLUDES ${CMAKE_CURRENT_SOURCE_DIR}/conan_provider.cmake)

> and included this file in CMakeLists.txt before project() command, it worked.

Ok, sounds like a possible workaround, until using the CMake recommended approach becomes possible to you.

**Closed as completed** 2023-11-22 04:52 UTC
