### ISSUE TITLE
Automatic conan settings detection issue

### ISSUE THREAD

**Issue by wawa19933** [conan-io/cmake-conan#182] opened 2019-10-23 06:31 UTC
## Summmary

There is an issue, when using `conan.cmake` in subdirectory, after `conan_basic_setup` is already invoked in parent project.

Below is the project structure:

```
/test-project
├── CMakeLists.txt
├── conanfile.py
└── sub-project
   ├── CMakeLists.txt
   └── conanfile.py
```

<details><summary>See CMake configure log</summary>
<p>

```log
-- The CXX compiler identification is GNU 9.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- COMPILE_OPTIONS= | COMPILE_DEFINITIONS= | /test-project
-- Downloading conan.cmake [v0.14] from https://github.com/conan-io/cmake-conan
-- Conan: checking conan executable in path
-- Conan: Found program /usr/bin/conan
-- Conan: Version found Conan version 1.18.4

-- Conan: Automatic detection of conan settings from cmake
-- Conan: Settings= -s;build_type=Release;-s;compiler=gcc;-s;compiler.version=9;-s;compiler.libcxx=libstdc++11
-- Conan executing: conan install /test-project/conanfile.py -s build_type=Release -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libstdc++11 -g=cmake -if=/test-project/cmake-build-test
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py (alice/0.1.1): Installing package
Requirements
Packages

conanfile.py (alice/0.1.1): Generator cmake created conanbuildinfo.cmake
conanfile.py (alice/0.1.1): Generator txt created conanbuildinfo.txt
conanfile.py (alice/0.1.1): Generated conaninfo.txt
conanfile.py (alice/0.1.1): Generated graphinfo
-- Conan: Loading conanbuildinfo.cmake
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: /test-project/cmake-build-test
-- Conan: Compiler GCC>=5, checking major version 9
-- Conan: Checking correct version: 9
-- COMPILE_OPTIONS=$<$<CONFIG:Debug>:>;$<$<CONFIG:Release>:>;$<$<CONFIG:RelWithDebInfo>:>;$<$<CONFIG:MinSizeRel>:> | COMPILE_DEFINITIONS= | /test-project
-- COMPILE_OPTIONS=$<$<CONFIG:Debug>:>;$<$<CONFIG:Release>:>;$<$<CONFIG:RelWithDebInfo>:>;$<$<CONFIG:MinSizeRel>:> | COMPILE_DEFINITIONS= | /test-project/sub-project
-- Downloading conan.cmake [v0.14] from https://github.com/conan-io/cmake-conan
-- Conan: checking conan executable in path
-- Conan: Found program /usr/bin/conan
-- Conan: Version found Conan version 1.18.4

-- Conan: Automatic detection of conan settings from cmake
c++: error: $<$<CONFIG:Debug>:>: No such file or directory
c++: error: $<$<CONFIG:Release>:>: No such file or directory
c++: error: $<$<CONFIG:RelWithDebInfo>:>: No such file or directory
c++: error: $<$<CONFIG:MinSizeRel>:>: No such file or directory
-- Conan: Settings= -s;build_type=Release;-s;compiler=gcc;-s;compiler.version=9;-s;compiler.libcxx=libc++
-- Conan executing: conan install /test-project/sub-project/conanfile.py -s build_type=Release -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libc++ -g=cmake -if=/test-project/cmake-build-test/sub-project
ERROR: Invalid setting 'libc++' is not a valid 'settings.compiler.libcxx' value.
Possible values are ['libstdc++', 'libstdc++11']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
CMake Error at cmake-build-test/sub-project/conan.cmake:399 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake-build-test/sub-project/conan.cmake:485 (conan_cmake_install)
  sub-project/CMakeLists.txt:43 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
```

</p>
</details>

<details><summary>CMakeLists.txt (same in subdirectory)</summary>
<p>

```cmake
cmake_minimum_required(VERSION 3.8)

project(Alice
    VERSION 0.1.1
    LANGUAGES CXX
)


# DEBUG {{{
    get_directory_property(__co DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} COMPILE_OPTIONS)
    get_directory_property(__cd DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} COMPILE_DEFINITIONS)
    message(STATUS "COMPILE_OPTIONS=${__co} | COMPILE_DEFINITIONS=${__cd} | ${CMAKE_CURRENT_SOURCE_DIR}")
    unset(__co)
    unset(__cd)
# }}}

if (CONAN_EXPORTED)
    include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    conan_basic_setup()
else(CONAN_EXPORTED)
    if(NOT CMAKE_CONAN_VERSION)
        set(CMAKE_CONAN_VERSION 0.14)
    endif(NOT CMAKE_CONAN_VERSION)

    # Download automatically, you can also just copy the conan.cmake file
    if(NOT EXISTS "${CMAKE_CURRENT_BINARY_DIR}/conan.cmake")
        message(STATUS "Downloading conan.cmake [v${CMAKE_CONAN_VERSION}] from https://github.com/conan-io/cmake-conan")
        file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/v${CMAKE_CONAN_VERSION}/conan.cmake"
            "${CMAKE_CURRENT_BINARY_DIR}/conan.cmake")
    endif()
    include(${CMAKE_CURRENT_BINARY_DIR}/conan.cmake)
    conan_check(REQUIRED)
    conan_cmake_run(CONANFILE conanfile.py BASIC_SETUP)
endif(CONAN_EXPORTED)


# DEBUG {{{
    get_directory_property(__co DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} COMPILE_OPTIONS)
    get_directory_property(__cd DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} COMPILE_DEFINITIONS)
    message(STATUS "COMPILE_OPTIONS=${__co} | COMPILE_DEFINITIONS=${__cd} | ${CMAKE_CURRENT_SOURCE_DIR}")
    unset(__co)
    unset(__cd)
# }}}

add_subdirectory(sub-project)
```

</p>
</details>

### Reason

After `conan_basic_setup` there are strange options populated via `COMPILE_OPTIONS` directory property: `COMPILE_OPTIONS=$<$<CONFIG:Debug>:>;$<$<CONFIG:Release>:>;$<$<CONFIG:RelWithDebInfo>:>;$<$<CONFIG:MinSizeRel>:>`

### Solution

Probably, it is issue in Conan CMake generator?
I can propose a quick fix to filter out such options when detecting settings.

**Comment by verbatom** [comment] 2019-10-23 11:42
duplicate of #140

**Comment by czoido** [comment] 2019-10-31 14:03
Hi @wawa19933,
Thanks for reporting, we are currently having a look at how to fix this issue.

**Closed** 2020-09-02 11:07 UTC
