### ISSUE TITLE
'cmake' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by redradist** [conan-io/cmake-conan#419] opened 2022-05-04 19:14 UTC
During testing the following packages using `cmake-conan`:
```console
[requires]
glfw/3.3.7
glew/2.2.0
flatbuffers/2.0.0

[generators]
cmake
```
and the following `CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.21)
project(LearnOpenGL)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_BINARY_DIR})

set(CMAKE_CXX_STANDARD 17)

option(OPENGL_WRAPPERS "Enables C++ wrappers" OFF)

if (OPENGL_WRAPPERS)
    add_definitions(-DOPENGL_WRAPPERS)
endif()

if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
    message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
    file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/0.18.1/conan.cmake"
         "${CMAKE_BINARY_DIR}/conan.cmake"
         TLS_VERIFY ON)
endif()

include(${CMAKE_BINARY_DIR}/conan.cmake)

conan_cmake_autodetect(settings)
conan_cmake_install(PATH_OR_REFERENCE ${CMAKE_CURRENT_LIST_DIR}
                    BUILD missing
                    REMOTE conancenter
                    SETTINGS ${settings})

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

add_executable(LearnOpenGLStarter main.cpp)
conan_target_link_libraries(LearnOpenGLStarter)
```
`conan` version 1.47.0, `cmake` version 3.21.1

Faced with the following error:
```console
flatbuffers/2.0.0: WARN: Build folder is dirty, removing it: <UserHomeDir>\.conan\data\flatbuffers\2.0.0\_\_\build\846e49ae2c2d7b4448ca2380ea2b4c7a382d695b
flatbuffers/2.0.0: Copying sources to build folder
flatbuffers/2.0.0: Building your package in <UserHomeDir>\.conan\data\flatbuffers\2.0.0\_\_\build\846e49ae2c2d7b4448ca2380ea2b4c7a382d695b
flatbuffers/2.0.0: Generator cmake created conanbuildinfo.cmake
flatbuffers/2.0.0: Aggregating env generators
flatbuffers/2.0.0: Calling build()
'cmake' is not recognized as an internal or external command,
operable program or batch file.
flatbuffers/2.0.0: flatbuffers/2.0.0: ERROR: Package '846e49ae2c2d7b4448ca2380ea2b4c7a382d695b' build failed

flatbuffers/2.0.0: WARN: Build folder <UserHomeDir>\.conan\data\flatbuffers\2.0.0\_\_\build\846e49ae2c2d7b4448ca2380ea2b4c7a382d695b
ERROR: flatbuffers/2.0.0: Error in build() method, line 125
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 120
	self._cmake.configure()
	ConanException: Error 1 while executing cd <UserHomeDir>\.conan\data\flatbuffers\2.0.0\_\_\build\846e49ae2c2d7b4448ca2380ea2b4c7a382d695b && cmake -G "Visual Studio 16 2019" -A "x64" -DCONAN_LINK_RUNTIME="/MDd" -DCONAN_CMAKE_CXX_STANDARD="17" -DCONAN_CMAKE_CXX_EXTENSIONS="OFF" -DCONAN_STD_CXX_FLAG="/std:c++17" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="16" -DCONAN_CXX_FLAGS="/MP8" -DCONAN_C_FLAGS="/MP8" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="<UserHomeDir>\.conan\data\flatbuffers\2.0.0\_\_\package\846e49ae2c2d7b4448ca2380ea2b4c7a382d695b" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DFLATBUFFERS_BUILD_TESTS="False" -DFLATBUFFERS_INSTALL="True" -DFLATBUFFERS_BUILD_FLATLIB="True" -DFLATBUFFERS_BUILD_FLATC="True" -DFLATBUFFERS_STATIC_FLATC="False" -DFLATBUFFERS_BUILD_FLATHASH="False" -DFLATBUFFERS_BUILD_SHAREDLIB="False" -DFLATBUFFERS_LIBCXX_WITH_CLANG="False" -DVERSION_MAJOR="2" -DVERSION_MINOR="0" -DVERSION_PATCH="0" -DCMAKE_POLICY_DEFAULT_CMP0042="NEW" -Wno-dev <UserHomeDir>\.conan\data\flatbuffers\2.0.0\_\_\build\846e49ae2c2d7b4448ca2380ea2b4c7a382d695b
CMake Error at cmake-build-debug-wrappers/conan.cmake:651 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  CMakeLists.txt:24 (conan_cmake_install)
```
It partially fixed with https://github.com/conan-io/conan/pull/11141 for similar issue with `git` command ...
It looks like it is not right to use commands in `conan` without specifying full path.
Sometimes it could work properly, but sometimes it could fail, see:
https://docs.python.org/3/library/subprocess.html#subprocess.Popen

take a look at warning section

**Comment by czoido** [comment] 2022-05-06 06:00
Hi @redradist,
I can't reproduce the issue and haven't seen any issues related with this before. I don't think this is related to cmake-conan. Could it be something related with your local setup? Are you sure the environment you are running into has the path to the cmake executable? Does a `which cmake` point to the cmake location?

**Comment by crsib** [comment] 2022-05-06 09:47
>I can't reproduce the issue and haven't seen any issues related with this before.

I saw this problem with a few developers. Usually it means that CMake is not PATH and run from the CMake GUI. Quite a usual case with macOS.

I think this case can be handled by cmake-conan though, as it has access to `${CMAKE_COMMAND}` and can pass it to `$ENV{CONAN_CMAKE_PROGRAM}`  if it is not set.

**Comment by redradist** [comment] 2022-05-06 12:05
@czoido You can reproduce this issue in CLion 2022.1
I also created issue in CLion https://youtrack.jetbrains.com/issue/CPP-29127/Clion-issue-with-cmake-conan-cmake-is-not-recognized-as-an-inter

Because it is hard to say bug in which tool it is ...

**Comment by redradist** [comment] 2022-05-06 12:07
> 

@crsib It is not my case, I printed all envoriement variable in conan before call of command and CMake was in PATH ...
Also by some reason this issue is only reproducible in CLion !!

All works properly in cmd or powershell

**Comment by czoido** [comment] 2022-05-06 12:15
> @czoido You can reproduce this issue in CLion 2022.1 I also created issue in CLion https://youtrack.jetbrains.com/issue/CPP-29127/Clion-issue-with-cmake-conan-cmake-is-not-recognized-as-an-inter
> 
> Because it is hard to say bug in which tool it is ...

@redradist, 
That is probably related to your IDE that's not able to load the PATH from the shell, maybe you can try to define the cmake path in the PATH environment variable inside the IDE configuration.
I think we can close this as this is not really related with cmake-conan.

**Closed as completed by czoido** 2022-05-06 12:15 UTC
Labels: question

**Comment by redradist** [comment] 2022-05-08 11:43
@czoido I am not sure it is an issue with Clion, because I added print statement in conan python file and before it printed all environment variables and cmake as well as git was in path ...
It could be fixed by specifying full path to Popen command https://github.com/conan-io/conan/pull/11141

**Comment by redradist** [comment] 2022-11-22 15:44
@czoido

Issue was related to Windows PATH environment variable longer than 8191 character.
Fixed in `conanex` removing duplicate paths, see https://github.com/redradist/conanex/blob/master/conanex/main.py#L23
