### ISSUE TITLE
【conan  install】conan_provider.cmake downloads packages from source because detect_host_profile generates compiler.cppstd=xx in the cmake-build-release/conan_host_profile file with the detect_host_profile method

### ISSUE THREAD

**Issue by chl1123** [conan-io/cmake-conan#638] opened 2024-04-18 02:52 UTC
I built my own private warehouse, and I wanted to manage the packages myself. I uploaded the boost package and wanted to download it from a private repository. When I downloaded the package, I found that instead of downloading the package built from the private repository, I built it from the downloaded source code.

This did not meet my expectations, and I wanted to download the built package from a private repository.

I found that the problem was the compiler.cppstd field in the generated cmake-build-release/conan_host_profile question, as follows:

The contents of my profile are as follows. I did not specify compiler.cppstd:
```
[settings]
os=Linux
arch=x86_64
compiler=clang
compiler.version=6.0
compiler.libcxx=libstdc++11
build_type=Release
```

I set up my own private repository, I uploaded the boost package and wanted to download it from my private repository, my steps were:
```
git clone https://github.com/conan-io/conan-center-index
cd conan-center-index/recipes/boost/all
# create boost
conan create . --build=missing --user=xxx --channel=xxx --version=1.84.0  --options=boost/1.84.0@xxx/xxx:shared=True

# Upload boost to a private repository
conan upload boost/1.84.0@xxx/xxx -r=xxx
```

Download boost from a private repository:
1. conanfile.txt
```
[requires]
boost/1.84.0@xxx/xxx

[generators]
CMakeDeps
CMakeToolchain

[layout]
cmake_layout
```
2. install boost
```
conan install conanfile.txt --build=missing
```

This is the output log from the download process, and I found that instead of downloading a built package from a private repository, I was building from source, which was not what I expected and was slow to build from source.
If you think the log is too long, you can go straight back to my summary.
```
-- CMake-Conan: first find_package() found. Installing dependencies with Conan
-- CMake-Conan: Checking if a default profile exists
/root/.conan2/profiles/default
-- CMake-Conan: cmake_system_name=Linux
-- CMake-Conan: cmake_system_processor=x86_64
-- CMake-Conan: CMake compiler=Clang
-- CMake-Conan: CMake compiler version=6.0.0
-- CMake-Conan: [settings] compiler=clang
-- CMake-Conan: [settings] compiler.version=6.0
-- CMake-Conan: Creating profile /home/chl/coding/rbk4-to-conan2/cmake-build-release/conan_host_profile
-- CMake-Conan: Profile:
[settings]
arch=x86_64
os=Linux
compiler=clang
compiler.version=6.0
compiler.cppstd=17
compiler.libcxx=libstdc++11
build_type=Release
[conf]
tools.cmake.cmaketoolchain:generator=Unix Makefiles
tools.build:compiler_executables={"c":"/usr/bin/cc","cpp":"/usr/bin/c++"}

-- CMake-Conan: Installing single configuration Release
-- CMake-Conan: conan install /home/chl/coding/rbk4-to-conan2 -of=/home/chl/coding/rbk4-to-conan2/cmake-build-release/conan --profile:host=default;--profile:host=/home/chl/coding/rbk4-to-conan2/cmake-build-release/conan_host_profile;--profile:build=default;--build=missing;-g;CMakeDeps
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=6.0
os=Linux
[conf]
tools.build:compiler_executables={'c': '/usr/bin/cc', 'cpp': '/usr/bin/c++'}
tools.cmake.cmaketoolchain:generator=Unix Makefiles

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++11
compiler.version=6.0
os=Linux
[conf]



======== Computing dependency graph ========
boost/1.84.0@x86_64/shared: Not found in local cache, looking in remotes...
boost/1.84.0@x86_64/shared: Checking remote: x86_64_linux_clang6
boost/1.84.0@x86_64/shared: Checking remote: conancenter
boost/1.84.0@x86_64/shared: Checking remote: conan2-local-chl
boost/1.84.0@x86_64/shared: Downloaded recipe revision 6787004aefbdc11aee9eb7c2d27d3e80
zlib/1.3.1@x86_64/chl: Not found in local cache, looking in remotes...
zlib/1.3.1@x86_64/chl: Checking remote: x86_64_linux_clang6
zlib/1.3.1@x86_64/chl: Checking remote: conancenter
zlib/1.3.1@x86_64/chl: Checking remote: conan2-local-chl
zlib/1.3.1@x86_64/chl: Downloaded recipe revision e20364c96c45455608a72543f3a53133
bzip2/1.0.8@x86_64/chl: Not found in local cache, looking in remotes...
bzip2/1.0.8@x86_64/chl: Checking remote: x86_64_linux_clang6
bzip2/1.0.8@x86_64/chl: Checking remote: conancenter
bzip2/1.0.8@x86_64/chl: Checking remote: conan2-local-chl
bzip2/1.0.8@x86_64/chl: Downloaded recipe revision 8779e3ee0cf27649212cd3fc0db4438b
libbacktrace/cci.20210118@x86_64/chl: Not found in local cache, looking in remotes...
libbacktrace/cci.20210118@x86_64/chl: Checking remote: x86_64_linux_clang6
libbacktrace/cci.20210118@x86_64/chl: Checking remote: conancenter
libbacktrace/cci.20210118@x86_64/chl: Checking remote: conan2-local-chl
libbacktrace/cci.20210118@x86_64/chl: Downloaded recipe revision f5d18dee9942ec36058b965afa867e7b
b2/4.10.1@x86_64/chl: Not found in local cache, looking in remotes...
b2/4.10.1@x86_64/chl: Checking remote: x86_64_linux_clang6
b2/4.10.1@x86_64/chl: Checking remote: conancenter
b2/4.10.1@x86_64/chl: Checking remote: conan2-local-chl
b2/4.10.1@x86_64/chl: Downloaded recipe revision 899c18f3a468c20da7ce7bd80c40d09d
Graph root
    conanfile.txt: /home/chl/coding/rbk4-to-conan2/conanfile.txt
Requirements
    boost/1.84.0@x86_64/shared#6787004aefbdc11aee9eb7c2d27d3e80 - Downloaded (conan2-local-chl)
    bzip2/1.0.8@x86_64/chl#8779e3ee0cf27649212cd3fc0db4438b - Downloaded (conan2-local-chl)
    libbacktrace/cci.20210118@x86_64/chl#f5d18dee9942ec36058b965afa867e7b - Downloaded (conan2-local-chl)
    zlib/1.3.1@x86_64/chl#e20364c96c45455608a72543f3a53133 - Downloaded (conan2-local-chl)
Build requirements
    b2/4.10.1@x86_64/chl#899c18f3a468c20da7ce7bd80c40d09d - Downloaded (conan2-local-chl)

======== Computing necessary packages ========
boost/1.84.0@x86_64/shared: Checking 7 compatible configurations
boost/1.84.0@x86_64/shared: Compatible configurations not found in cache, checking servers
boost/1.84.0@x86_64/shared: '8babe0a09cb33647df218d735f040b08c657ed1a': compiler.cppstd=11
boost/1.84.0@x86_64/shared: '2a8eeda5e4b5f38f628a01560ea627a9a4c01f7f': compiler.cppstd=gnu11
boost/1.84.0@x86_64/shared: 'b03c2218a13540bab1a69df91b0bccc01cbb8340': compiler.cppstd=14
boost/1.84.0@x86_64/shared: '0cea42f4b97568a96f0f56fda1ee002d85dcb1f7': compiler.cppstd=gnu14
boost/1.84.0@x86_64/shared: '8552e8b3c558234acbdb08293d8814bceb9c9b3b': compiler.cppstd=gnu17
boost/1.84.0@x86_64/shared: '330201d5c5140fdaf8f0311a3c16a21f08d9742f': compiler.cppstd=20
boost/1.84.0@x86_64/shared: '1b03d05498778d62a132a0e9e24630098041d3ca': compiler.cppstd=gnu20
Requirements
    boost/1.84.0@x86_64/shared#6787004aefbdc11aee9eb7c2d27d3e80:d48cf38a15579d831ef994502f431f8aa9e73e18 - Build
    bzip2/1.0.8@x86_64/chl#8779e3ee0cf27649212cd3fc0db4438b:f87aa3d38badf98a25dae9637589fa8b159a4f4c#fa587ae6b220c73b4ac44d7874a4ec41 - Download (conan2-local-chl)
    libbacktrace/cci.20210118@x86_64/chl#f5d18dee9942ec36058b965afa867e7b:c816c14f2843fd5d8b2089f1ab550ebb63b841ca#e382f1cd7f63f17734062be17e5773b3 - Download (conan2-local-chl)
    zlib/1.3.1@x86_64/chl#e20364c96c45455608a72543f3a53133:c816c14f2843fd5d8b2089f1ab550ebb63b841ca#8aa8fa58712f4fc5eaff35290864e5f7 - Download (conan2-local-chl)
Build requirements
    b2/4.10.1@x86_64/chl#899c18f3a468c20da7ce7bd80c40d09d:63fead0844576fc02943e16909f08fcdddd6f44b#85cb641f9ef7a92a6291d51794134a96 - Download (conan2-local-chl)

======== Installing packages ========

-------- Downloading 4 packages --------
b2/4.10.1@x86_64/chl: Retrieving package 63fead0844576fc02943e16909f08fcdddd6f44b from remote 'conan2-local-chl'
b2/4.10.1@x86_64/chl: Package installed 63fead0844576fc02943e16909f08fcdddd6f44b
b2/4.10.1@x86_64/chl: Downloaded package revision 85cb641f9ef7a92a6291d51794134a96
bzip2/1.0.8@x86_64/chl: Retrieving package f87aa3d38badf98a25dae9637589fa8b159a4f4c from remote 'conan2-local-chl'
bzip2/1.0.8@x86_64/chl: Package installed f87aa3d38badf98a25dae9637589fa8b159a4f4c
bzip2/1.0.8@x86_64/chl: Downloaded package revision fa587ae6b220c73b4ac44d7874a4ec41
libbacktrace/cci.20210118@x86_64/chl: Retrieving package c816c14f2843fd5d8b2089f1ab550ebb63b841ca from remote 'conan2-local-chl'
libbacktrace/cci.20210118@x86_64/chl: Package installed c816c14f2843fd5d8b2089f1ab550ebb63b841ca
libbacktrace/cci.20210118@x86_64/chl: Downloaded package revision e382f1cd7f63f17734062be17e5773b3
zlib/1.3.1@x86_64/chl: Retrieving package c816c14f2843fd5d8b2089f1ab550ebb63b841ca from remote 'conan2-local-chl'
zlib/1.3.1@x86_64/chl: Package installed c816c14f2843fd5d8b2089f1ab550ebb63b841ca
zlib/1.3.1@x86_64/chl: Downloaded package revision 8aa8fa58712f4fc5eaff35290864e5f7
boost/1.84.0@x86_64/shared: Sources downloaded from 'conan2-local-chl'
boost/1.84.0@x86_64/shared: Calling source() in /root/.conan2/data/boost556c9b3d1247c/s/src
boost/1.84.0@x86_64/shared: Downloading 123.1MB boost_1_84_0.tar.bz2
boost/1.84.0@x86_64/shared: Downloaded 69.5MB 56% boost_1_84_0.tar.bz2
boost/1.84.0@x86_64/shared: Downloaded 100.5MB 81% boost_1_84_0.tar.bz2
boost/1.84.0@x86_64/shared: Downloaded 112.1MB 91% boost_1_84_0.tar.bz2
boost/1.84.0@x86_64/shared: Downloaded 118.7MB 96% boost_1_84_0.tar.bz2
boost/1.84.0@x86_64/shared: Apply patch (conan): Optional flag to specify iconv from either libc of libiconv
boost/1.84.0@x86_64/shared: Apply patch (official): Fix compilation with cppstd=20 on libcxx platforms (e.g. MacOS)
```

It's in the log：`-- CMake-Conan: conan install XXX -of=XXX/cmake-build-release/conan --profile:host=default;--profile:host=XXX/cmake-build-release/conan_host_profile;--profile:build=default;--build=missing;-g;CMakeDeps`。
After a series of debugging, I found that the problem was with the detect_host_profile() method in the conan_provider.cmake file
```
    if(MYCXX_STANDARD)
        string(APPEND PROFILE compiler.cppstd=${MYCXX_STANDARD} "\n")
    endif()
```
The above three lines of code generate the cmake-build-release/conan_host_profile file under the project
```
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=6.0
os=Linux
[conf]
tools.build:compiler_executables={'c': '/usr/bin/cc', 'cpp': '/usr/bin/c++'}
tools.cmake.cmaketoolchain:generator=Unix Makefiles
```

I'll just comment these three lines of code in the detect_host_profile() method in the conan_provider.cmake file
conan_provider.cmake
```
#    if(MYCXX_STANDARD)
#        string(APPEND PROFILE compiler.cppstd=${MYCXX_STANDARD} "\n")
#    endif()
```
Generate the cmake-build-release/conan_host_profile file
```
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++11
compiler.version=6.0
os=Linux
[conf]
tools.build:compiler_executables={'c': '/usr/bin/cc', 'cpp': '/usr/bin/c++'}
tools.cmake.cmaketoolchain:generator=Unix Makefiles
```
When you download boost from the private library, the built package is downloaded directly, with log output
```
-- CMake-Conan: first find_package() found. Installing dependencies with Conan
-- CMake-Conan: Checking if a default profile exists
/root/.conan2/profiles/default
-- CMake-Conan: cmake_system_name=Linux
-- CMake-Conan: cmake_system_processor=x86_64
-- CMake-Conan: CMake compiler=Clang
-- CMake-Conan: CMake compiler version=6.0.0
-- CMake-Conan: [settings] compiler=clang
-- CMake-Conan: [settings] compiler.version=6.0
-- CMake-Conan: Creating profile /home/chl/coding/rbk4-to-conan2/cmake-build-release/conan_host_profile
-- CMake-Conan: Profile: 
[settings]
arch=x86_64
os=Linux
compiler=clang
compiler.version=6.0
compiler.libcxx=libstdc++11
build_type=Release
[conf]
tools.cmake.cmaketoolchain:generator=Unix Makefiles
tools.build:compiler_executables={"c":"/usr/bin/cc","cpp":"/usr/bin/c++"}

-- CMake-Conan: Installing single configuration Release
-- CMake-Conan: conan install /home/chl/coding/rbk4-to-conan2 -of=/home/chl/coding/rbk4-to-conan2/cmake-build-release/conan --profile:host=default;--profile:host=/home/chl/coding/rbk4-to-conan2/cmake-build-release/conan_host_profile;--profile:build=default;--build=missing;-g;CMakeDeps
-- CMake-Conan: conan install /home/chl/coding/rbk4-to-conan2 -of=/home/chl/coding/rbk4-to-conan2/cmake-build-release/conan --profile:host=default;--profile:host=/home/chl/coding/rbk4-to-conan2/cmake-build-release/conan_host_profile;--profile:build=default;--build=missing;-g;CMakeDeps  --format=json

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++11
compiler.version=6.0
os=Linux
[conf]
tools.build:compiler_executables={'c': '/usr/bin/cc', 'cpp': '/usr/bin/c++'}
tools.cmake.cmaketoolchain:generator=Unix Makefiles

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++11
compiler.version=6.0
os=Linux
[conf]



======== Computing dependency graph ========
boost/1.84.0@x86_64/shared: Not found in local cache, looking in remotes...
boost/1.84.0@x86_64/shared: Checking remote: x86_64_linux_clang6
boost/1.84.0@x86_64/shared: Checking remote: conancenter
boost/1.84.0@x86_64/shared: Checking remote: conan2-local-chl
boost/1.84.0@x86_64/shared: Downloaded recipe revision 6787004aefbdc11aee9eb7c2d27d3e80
Graph root
    conanfile.txt: /home/chl/coding/rbk4-to-conan2/conanfile.txt
Requirements
    boost/1.84.0@x86_64/shared#6787004aefbdc11aee9eb7c2d27d3e80 - Downloaded (conan2-local-chl)
    bzip2/1.0.8@x86_64/chl#8779e3ee0cf27649212cd3fc0db4438b - Cache
    libbacktrace/cci.20210118@x86_64/chl#f5d18dee9942ec36058b965afa867e7b - Cache
    zlib/1.3.1@x86_64/chl#e20364c96c45455608a72543f3a53133 - Cache
Build requirements
    b2/4.10.1@x86_64/chl#899c18f3a468c20da7ce7bd80c40d09d - Cache

======== Computing necessary packages ========
Requirements
    boost/1.84.0@x86_64/shared#6787004aefbdc11aee9eb7c2d27d3e80:f4d8e0b47c299a17303946becf37a013cd661fe6#9d2c1ad7a0aa4945ce78fa23515a4ada - Download (conan2-local-chl)
    libbacktrace/cci.20210118@x86_64/chl#f5d18dee9942ec36058b965afa867e7b:c816c14f2843fd5d8b2089f1ab550ebb63b841ca#e382f1cd7f63f17734062be17e5773b3 - Cache
Build requirements
Skipped binaries
    bzip2/1.0.8@x86_64/chl, zlib/1.3.1@x86_64/chl, b2/4.10.1@x86_64/chl

======== Installing packages ========

-------- Downloading 1 package --------
boost/1.84.0@x86_64/shared: Retrieving package f4d8e0b47c299a17303946becf37a013cd661fe6 from remote 'conan2-local-chl' 
boost/1.84.0@x86_64/shared: Downloading 19.4MB conan_package.tgz
boost/1.84.0@x86_64/shared: Decompressing 19.4MB conan_package.tgz
boost/1.84.0@x86_64/shared: Package installed f4d8e0b47c299a17303946becf37a013cd661fe6
boost/1.84.0@x86_64/shared: Downloaded package revision 9d2c1ad7a0aa4945ce78fa23515a4ada
libbacktrace/cci.20210118@x86_64/chl: Already installed! (1 of 2)
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'env_info' used in: boost/1.84.0@x86_64/shared
WARN: deprecated:     'cpp_info.filenames' used in: boost/1.84.0@x86_64/shared
WARN: deprecated:     'cpp_info.names' used in: boost/1.84.0@x86_64/shared
WARN: deprecated:     'user_info' used in: boost/1.84.0@x86_64/shared
```

I realized that this could be a problem of inconsistency between the conan2 configuration file and the generated configuration file, so I added compiler.cppstd to the profile:
```
[settings]
os=Linux
arch=x86_64
compiler=clang
compiler.version=6.0
compiler.libcxx=libstdc++11
compiler.cppstd=17
build_type=Release
```
After running again, it is found that there will still be a download from the source code, is this a bug

**Comment by memsharded** [comment] 2024-04-18 08:21
Hi @chl1123 

Thanks for your question.

> The contents of my profile are as follows. I did not specify compiler.cppstd:

I think this is the key. 
In Conan 2 it is extremely recommended to define it. 
- Built-in integrations will use it to define the current cppstd. Otherwise it will be the build scripts hardcoding it sometimes to different values, and this can cause issues
- The cppstd might affect the binary compatibility in some cases
- The cppstd is true that is quite binary compatible. But the default ``compatibility.py`` plugin already handles this compatibility and it is able to fallback to other cppstd binaries (but prioritizing the defined one).

> After running again, it is found that there will still be a download from the source code, is this a bug

No, it wouldn't be a bug, because the behavior of ``cmake-conan`` is aligned with the default expected behavior of Conan client.

I'd strongly recommend to define ``compiler.cppstd`` for your builds.

**Comment by chl1123** [comment] 2024-04-18 09:25
Thank you. I deleted the package from the private repository and re-uploaded it successfully

**Comment by memsharded** [comment] 2024-04-18 16:02
Ok, thanks for the feedback!

Then, with the recommendation to use ``compiler.cppstd``, all good? Maybe we can close this issue?

**Comment by chl1123** [comment] 2024-04-19 03:56
Yeah, I already took care of it. I had to delete the original boost package in the private repository first, then add the compiler.cppstd configuration and re-upload it to make it work.
If I do not remove the boost package of the private repository, the direct upload after modifying the compiler.cppstd will fail.

**Comment by memsharded** [comment] 2024-04-19 11:35
Thanks for the feedback, closing the ticket then. Don't hesitate to create new ones for any further question

**Closed as completed by memsharded** 2024-04-19 11:35 UTC
