### ISSUE TITLE
MSVC version update

### ISSUE THREAD

**Issue by sersoftin** [conan-io/cmake-conan#646] opened 2024-06-06 11:33 UTC
The Microsoft compiler has been updated and is no longer able to run conan install from conan.cmake.
Please fix this for cmake wrapper 0.18.1.

**Comment by memsharded** [comment] 2024-06-06 11:42
Hi @sersoftin 

Thanks for your report.

Please check the warnings and readmes in the repo. Conan 1 is no longer the recommended version, and cmake-conan version 0.18.1 is for Conan 1. Conan 2 was released 16 months ago already, and the recommended version is the one using CMake providers, that has already been updated.

In any case, I think the fix you are looking for is the one in https://github.com/conan-io/cmake-conan/pull/643, which has been merged to ``develop`` branch. There are no new releases planned for Conan 1 ``cmake-conan``, so you might try to use it from ``develop`` branch instead.

**Comment by sersoftin** [comment] 2024-06-10 14:20
@memsharded  Thanks.

**Comment by tbeu** [comment] 2024-06-11 19:10
Same issue here: https://github.com/tbeu/matio/actions/runs/9456015260/job/26047052662?pr=249#step:5:40

Can you please create a new release - either C1 or C2 - where the issue is fixed. Thanks.

**Comment by memsharded** [comment] 2024-06-11 20:37
The ``develop2`` branch is considered stable and good enough for production, it can be used in projects (it is already being used by the CLion integration).

The recommended approach is to download a copy an put it in the project, so it can be used easily just by cloning the project.

Conan 1 will not get more releases for ``cmake-conan``. For Conan 2 there will be a release, but not immediately, please use the ``develop2`` in the meantime.

**Comment by tbeu** [comment] 2024-06-12 05:08
Thanks for the reply.

> The recommended approach is to download a copy an put it in the project, so it can be used easily just by cloning the project.

I already did and was able to [patch manually](https://github.com/tbeu/matio/commit/9a7244f95d1027b87d4576231356216b577895ed).

**Comment by memsharded** [comment] 2024-06-12 10:13
Sounds good, thanks for the feedback.

I am closing this ticket as resolved, keep tuned to the repo for the first numbered releases with the Conan 2 `cmake-conan` integration.

**Closed as completed by memsharded** 2024-06-12 10:13 UTC
